version: '3.8'

services:
  backend:
    image: backend
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    image: frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
